import { fakerEN_IN as faker } from "@faker-js/faker";
import type { LeadData } from "../shared/types.js";

const cities = ["Ahmedabad", "Surat", "Mumbai", "Pune", "Bengaluru", "Delhi", "Hyderabad", "Jaipur"];
const sources = ["Website", "Referral", "IndiaMART", "LinkedIn", "Google Ads", "Walk-in"];
const statuses = ["New", "Contacted", "Qualified", "Follow-up"];
const requirements = ["CRM demo", "ERP integration", "Website redesign", "Support automation", "Lead management"];

export function createRandomLeadData(): LeadData {
  const firstName = faker.person.firstName();
  const lastName = faker.person.lastName();
  return {
    name: `${firstName} ${lastName}`,
    phone: faker.phone.number({ style: "national" }),
    email: faker.internet.email({ firstName, lastName }).toLowerCase(),
    company: `${faker.company.name()} Pvt Ltd`,
    city: faker.helpers.arrayElement(cities),
    source: faker.helpers.arrayElement(sources),
    notes: `This is QA test lead generated by local agent. ${faker.lorem.sentence()}`,
    status: faker.helpers.arrayElement(statuses),
    requirement: faker.helpers.arrayElement(requirements)
  };
}

export function createRandomLeads(count: number): LeadData[] {
  return Array.from({ length: count }, createRandomLeadData);
}
